name: "Vocera Run Test Auto"
description: "Run scenarios against Vocera agents"
author: "Vocera AI"

runs:
  using: "composite"
  steps:
    - name: Run Scenarios
      uses: vocera-ai/vocera-run-test-auto/.github/workflows/deploy.yml
      env:
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
        API_KEY: ${{ secrets.API_KEY }}
        AGENT_ID: ${{ env.AGENT_ID }}
        SCENARIOS: ${{ env.SCENARIOS }}
        FREQUENCY: ${{ env.FREQUENCY }}
        TIMEOUT: ${{ env.TIMEOUT }}
        POLL_INTERVAL: ${{ env.POLL_INTERVAL }}

branding:
  icon: "play-circle"
  color: "blue"
