name: Vocera Run Test Auto

on:
    pull_request:
      branches:
        - main

jobs:
  run-scenarios:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run scenarios
      env:
        API_BASE_URL: ${{ env.API_BASE_URL }}
        API_KEY: ${{ env.API_KEY }}
        AGENT_ID: ${{ env.AGENT_ID }}
        SCENARIOS: ${{ env.SCENARIOS }}
        FREQUENCY: ${{ env.FREQUENCY }}
        TIMEOUT: ${{ env.TIMEOUT }}
        POLL_INTERVAL: ${{ env.POLL_INTERVAL }}
      run: python run_scenarios.py
